project:
  type: website

website:
  title: CONQUER THE HILL
  favicon: /images/conquerTheHillLogo2024-2.png
  twitter-card: true
  open-graph:
    site-name: "️🌅 CONQUER THE HILL 2024"
    locale: en_US
  site-url: https://conquerthehilltucson.com/
  navbar:
    right:
      - text: Event
        href: index.qmd
      - text: Charities
        menu:
          - href: iAmYou360.qmd
          - href: tucsonVeteransServingVeterans.qmd
          - href: teenChallengeAZ.qmd
      - text: About
        href: about.qmd
        

format:
  html:
    page-layout: full
    theme:
      light: [darkly, style/custom.scss]
    linkcolor: "#D59319" 
    toc: true
    code-copy: true
    code-overflow: wrap
    include-before-body: particles.html
    resources: ["data"]

execute:
  freeze: auto
