project:
  type: website

website:
  title: ⛰️ CONQUER THE HILL 2023
  favicon: /images/conquerTheHillLogo.jpeg
  twitter-card: true
  open-graph:
    site-name: "⛰️ CONQUER THE HILL 2023"
    locale: en_US
  site-url: https://fluffy-cassata.netlify.app/
  navbar:
    right:
      - text: Event
        href: index.qmd
      - text: Charities
        menu:
          - href: casaDeLosNinos.qmd
          - href: gospelRescueMission.qmd
          - href: handUpNotOut.qmd
          - href: iAmYou360.qmd
          - href: laFronteraArizona.qmd
      - text: About
        href: about.qmd
        

format:
  html:
    page-layout: full
    theme:
      light: [cosmo, style/custom.scss]
    linkcolor: "#866fa3" 
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
